### ISSUE TITLE
grtfmi delivers different output than rtwsfcnfmi target

### ISSUE THREAD

**Issue by StefanMa-hub** [CATIA-Systems/FMIKit-Simulink#154] opened 2020-04-15 07:46 UTC
Building a simple integrator with step size 1 ms delivers two different outputs with different targets. The fmu built with the rtwsfcnfmi target delivers the same output than the simulink model, just delayed by 1 ms. The built with the grtfmi target delivers an output which is fitting 2 s to the simulink model output and then something strange is happing. Check the picture in the attachements. The blue line is the fmu output of the integrator, yellow is the model. We have the same behaviour in Simulink and in Silver.

**Comment by t-sommer** [comment] 2020-04-15 11:43
![image001](https://user-images.githubusercontent.com/2453858/79333548-08687a80-7f1f-11ea-898a-0f29f6ba3201.png)

**Comment by fajansen** [comment] 2020-04-15 11:58
I think the issue might be floating point accuracy in in fmi2DoStep in line:
while (rtmGetT(instance->S) + STEP_SIZE < tNext + DBL_EPSILON)
DBL_EPSILON is the accuracy at a floating point value of 1, but if tNext is not 1, you do not reliably determine if a step needs to be computed.

**Comment by t-sommer** [comment] 2020-04-15 12:34
Duplicate of #133.

**Closed by t-sommer** 2020-04-15 12:34 UTC
Labels: duplicate
