### ISSUE TITLE
Get and Set FMU states

### ISSUE THREAD

**Issue by Tulgs** [CATIA-Systems/FMIKit-Simulink#334] opened 2022-02-14 12:37 UTC
I wanted to ask if there will be an implementation for the functions for getting and setting the internal FMU state (fmi2GetFMUstate(), fmi2SetFMUstate(), fmi2SerializeFMUstate() etc.) for grtfmi.tlc and rtwsfcnfmi.tlc in a near release? If not, is it even possible to implement them in the FMIKit? I didn't find any C Implementation yet that fully supports those functionalities, so that I could maybe understand the behavior and implement it on my own. Thanks for your help.

**Comment by t-sommer** [comment] 2022-02-16 13:07
Closing as duplicate of #226.

**Closed by t-sommer** 2022-02-16 13:07 UTC
Labels: duplicate
