### ISSUE TITLE
Erratic stepping behavior in FMU exported with grtfmi

### ISSUE THREAD

**Issue by eidekrist** [CATIA-Systems/FMIKit-Simulink#133] opened 2020-01-17 14:28 UTC
This was discovered while comparing an FMU exported from Simulink using FMIKit grtfmi to an FMU generated with a different toolbox. 

System: MATLAB 2018b, Windows, Visual Studio 2017, FMI version 2.0.

Comparing the outputs of the two FMUs, the outputs of the grtfmi-generated FMU were showing erratic behavior; sometimes the output values were lagging behind one step, sometimes they were the same, and sometimes they were leading with one step. I believe it is related to the following line of code in the `fmi2DoStep()` method in `fmi2Functions.c`:
```C
while (rtmGetT(instance->S) + STEP_SIZE < tNext + DBL_EPSILON)
```
In my case, the inaccuracies on both sides of the comparator were at times larger than `DBL_EPSILON`. This resulted in that one call to `fmi2DoStep()` could result in `MODEL_STEP()` not being called, or being called twice.

While it may not be a good solution for all use cases, what worked for me was increasing the tolerance by replacing `DBL_EPSILON` with `STEP_SIZE * 0.5` in the above mentioned line of code.

**Comment by t-sommer** [comment] 2020-01-17 16:36
Can you share a model to reproduce the problem?

**Comment by eidekrist** [comment] 2020-01-20 08:06
I have attached a zip containing a demo model and two win64 FMUs generated from it, where one is patched according to my description above. The step size I am using is 0.04 s.
[step_demo.zip](https://github.com/CATIA-Systems/FMIKit-Simulink/files/4085047/step_demo.zip)

**Comment by t-sommer** [comment] 2020-01-20 12:29
> output values were lagging behind one step, sometimes they were the same

I can reproduce the problem with FMPy and the command `fmpy --fmi-logging simulate step_demo.fmu` (I've added a clock as a third output `vr=5`).

```
...
[FMI] fmi2DoStep(component=0x1a4e59c84a0, currentCommunicationPoint=8.120000000000003, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1a4e59c84a0, vr=[3, 4, 5], nvr=3, value=[1.3012669440633386, -0.3012643846589916, 8.16]) -> OK
[FMI] fmi2DoStep(component=0x1a4e59c84a0, currentCommunicationPoint=8.160000000000002, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1a4e59c84a0, vr=[3, 4, 5], nvr=3, value=[1.3391573882902101, -0.3391548609838345, 8.2]) -> OK
[FMI] fmi2DoStep(component=0x1a4e59c84a0, currentCommunicationPoint=8.200000000000001, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1a4e59c84a0, vr=[3, 4, 5], nvr=3, value=[1.3765052530469566, -0.3765027618802833, 8.24]) -> OK
[FMI] fmi2DoStep(component=0x1a4e59c84a0, currentCommunicationPoint=8.24, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1a4e59c84a0, vr=[3, 4, 5], nvr=3, value=[1.3765052530469566, -0.3765027618802833, 8.24]) -> OK
[FMI] fmi2DoStep(component=0x1a4e59c84a0, currentCommunicationPoint=8.28, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1a4e59c84a0, vr=[3, 4, 5], nvr=3, value=[1.4132507897170872, -0.41324833867402755, 8.28]) -> OK
[FMI] fmi2DoStep(component=0x1a4e59c84a0, currentCommunicationPoint=8.319999999999999, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x1a4e59c84a0, vr=[3, 4, 5], nvr=3, value=[1.4493352132805593, -0.4493328062808388, 8.32]) -> OK
...
```

> sometimes they were leading with one step

Can you provide steps to reproduce this or maybe a log of the FMI calls?

**Comment by eidekrist** [comment] 2020-01-20 13:14
Thanks for looking into it!

> > sometimes they were leading with one step
> 
> Can you provide steps to reproduce this or maybe a log of the FMI calls?

After further investigation I believe I may have confused this part with something else. Apologies if I have wasted any of your time here.

**Comment by t-sommer** [comment] 2020-02-05 09:50
@eidekrist, can you check if the problem is resolved with the [latest version of FMPy](https://github.com/CATIA-Systems/FMPy/releases/tag/v0.2.17)?

**Comment by eidekrist** [comment] 2020-02-05 12:55
I have downloaded and run FMPy 0.2.17, looks like the problem is still there. The below output shows a hiccup occuring at `currentCommunicationPoint=1.96` (I also added clock as a third output `vr=5`):

```
...
[FMI] fmi2DoStep(component=0x23c0c046eb0, currentCommunicationPoint=1.8800000000000001, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c046eb0, vr=[3, 4, 5], nvr=3, value=[1.342152175726763, -0.3421496511508982, 1.92]) -> OK
[FMI] fmi2DoStep(component=0x23c0c046eb0, currentCommunicationPoint=1.92, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c046eb0, vr=[3, 4, 5], nvr=3, value=[1.3794542529048648, -0.3794517647881545, 1.96]) -> OK
[FMI] fmi2DoStep(component=0x23c0c046eb0, currentCommunicationPoint=1.96, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c046eb0, vr=[3, 4, 5], nvr=3, value=[1.3794542529048648, -0.3794517647881545, 1.96]) -> OK
[FMI] fmi2DoStep(component=0x23c0c046eb0, currentCommunicationPoint=2.0, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c046eb0, vr=[3, 4, 5], nvr=3, value=[1.4161492842256644, -0.4161468365471424, 2.0]) -> OK
...
```

**Comment by t-sommer** [comment] 2020-02-05 23:49
With 08959395486d3bbbbb4efae3ee51a59f5ab2e940 I get no more hickups.

**Comment by eidekrist** [comment] 2020-02-06 10:00
That was my initial impression as well, but then I left the simulation running for some time, and got a hiccup at `t=255.96`:
```
...
[FMI] fmi2DoStep(component=0x23c0c047db0, currentCommunicationPoint=255.88, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c047db0, vr=[3, 4, 5], nvr=3, value=[1.1195122620849511, -0.11951490165164468, 255.92000000000002]) -> OK
[FMI] fmi2DoStep(component=0x23c0c047db0, currentCommunicationPoint=255.92000000000002, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c047db0, vr=[3, 4, 5], nvr=3, value=[1.0797139432161422, -0.07971659556520329, 255.96]) -> OK
[FMI] fmi2DoStep(component=0x23c0c047db0, currentCommunicationPoint=255.96, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c047db0, vr=[3, 4, 5], nvr=3, value=[1.0797139432161422, -0.07971659556520329, 255.96]) -> OK
[FMI] fmi2DoStep(component=0x23c0c047db0, currentCommunicationPoint=256.0, communicationStepSize=0.04, noSetFMUStatePriorToCurrentPoint=1) -> OK
[FMI] fmi2GetReal(component=0x23c0c047db0, vr=[3, 4, 5], nvr=3, value=[1.0397880990443442, -0.03979075993115771, 256.0]) -> OK
...
```

While increasing the tolerance to `100 * DBL_EPSILON` helps, is there a good reason for not using the (in my opinion) logical tolerance value of `0.5 * STEP_SIZE`? 

Then again, increasing the tolerance might only postpone the problem to later in the simulation. If the step size does not have an exact representation as a double, wouldn't accumulating time as `time = n_steps * stepSize` mean that the "error" in the step size value scales with `n_steps`?

**Comment by t-sommer** [comment] 2020-02-06 20:55
> is there a good reason for not using the (in my opinion) logical tolerance value of 0.5 * STEP_SIZE?

You cannot make any assumptions about the communication intervals. If the master uses a variable step size this could make the FMU "step ahead" of the current time.

**Comment by t-sommer** [comment] 2020-02-06 21:01
With 7cb1474c334eba6b27e08a38a4aa0861424d8fa2 I get no more hiccups:

```python
from fmpy import *
import numpy as np

result = simulate_fmu('step_demo.fmu', output_interval=0.04, stop_time=500, output=['Out1'])

print("Hiccups?", np.any(np.diff(result['Out1']) == 0))
```

**Comment by eidekrist** [comment] 2020-02-07 07:54
> If the master uses a variable step size this could make the FMU "step ahead" of the current time.

Of course, didn't consider that.


> With [7cb1474](https://github.com/CATIA-Systems/FMIKit-Simulink/commit/7cb1474c334eba6b27e08a38a4aa0861424d8fa2) I get no more hiccups:

Same here, works beautifully. Thanks!

**Comment by t-sommer** [comment] 2020-02-07 21:08
Thanks for your patience!

**Closed by t-sommer** 2020-02-07 21:08 UTC
