### ISSUE TITLE
Simulink output vector gets mixed up in Dymola

### ISSUE THREAD

**Issue by PhilippZofer** [CATIA-Systems/FMIKit-Simulink#69] opened 2019-09-06 12:56 UTC
The output signals of a FMU get mixed up and do not react to changed parameters, if the output port in MATLAB/Simulink is a vector.

As an example a sine wave block vector and a output port vector are used. The sine wave block creates 5 different sine waves. The model is exported from MATLAB/Simulink with the FMI-Kit. This request is a follow up to issue #68 .

FMU Export 
-------------------------------------------------------------
The model and the FMU are attached - download [here](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3583960/vectorOutputs.zip)
**Modeling Tool - MATLAB/Simulink R2018b**
Model
*  1 vector Sine Wave Block connected to one vector output port
*  Amplitude: 1
*  Frequency: 1, 5, 15, 25, 100 Hz
    
**Export Tool - FMI-Kit 2.6.0**
Settings:
*  Solver Type: Fixed-step
*  Code Geneneration -> System target file: grtfmi.tlc
*  Code Generation/FMI -> CMake generator: MinGW Makefiles

Steps
--------
1. Import the attached [FMU](https://github.com/CATIA-Systems/FMIKit-Simulink/files/3583960/vectorOutputs.zip) to Dymola (or FMPy)
2. change communictionStepSize: FMU block -> FMI -> fmi_CommunicationStepSize = 0.001 (due to #68 )
3. Simulate
4. see Results:
    `vectorSineWave_fmu1.Out1` -> should have 1 Hz, but has 100 Hz (only in Dymola)
    `vectorSineWave_fmu1.Out2` -> should have 5 Hz - ok
    `vectorSineWave_fmu1.Out3` -> should have 15 Hz - ok
    `vectorSineWave_fmu1.Out4` -> should have 25 Hz - ok
    `vectorSineWave_fmu1.Out5` -> should have 100 Hz - ok
5. change Frequency and Amplitude
6. see results:
    Signal `vectorSineWave_fmu1.Out1` reacts to Amplitude input of `vectorSineWave_fmu1.Out5`
    all other signals stay the same

Problem
-----------
The behaviour with different vector sizes is the same: the first output has the frequency of the last output and reacts only to the Amplitude input for the last output. The same behaviour was observerd, when in Simulink the sine wave block vector was split up with a 'Demux' Block into 5 scalar signals with on scalar output port each.

Expected Result
----------------------
In step 4. the signal `vectorSineWave_fmu1.Out1` should have its default frequency and not the frequency of the last signal (only in Dymola).
In step 6. we would expect every signal to change amplitude and frequency according to the given inputs.

**Comment by t-sommer** [comment] 2019-09-06 18:06
Thanks for sharing your insights, @PhilippZofer. Can you reproduce the issues in #68 and #69 with the latest version of develop?

**Comment by t-sommer** [comment] 2019-09-06 18:15
Here's what I get with FMPy:

![vectorSineWave_FMPy_GUI](https://user-images.githubusercontent.com/2453858/64450710-01ed6700-d0e3-11e9-9258-343d0abbf5aa.png)

**Comment by PhilippZofer** [comment] 2019-09-11 14:19
Unfortunately I can reproduce the issues #68 and #69 in Dymola with the latest version of the develop branch
![DymolaWindow](https://user-images.githubusercontent.com/51989887/64704569-ce2d8b00-d4ae-11e9-93db-e5306cef4b54.png)

Steps I did:

1. switch branch on the github site to 'develop' and downloaded as ZIP
2. replaced the `grtfmi ` folder with the downloaded folder

> C:\Users\<Name>\AppData\Roaming\MathWorks\MATLAB Add-Ons\FMIKit\grtfmi

3. standard FMU Export + import to Dymola + simulation

Was this correct or should I have replaced more?

**Comment by PhilippZofer** [comment] 2019-09-11 14:36
In FMPy only issue #68 is recognizable. In Dymola both issues (#68 and #69) occure:
![grafik](https://user-images.githubusercontent.com/51989887/64706484-d3d8a000-d4b1-11e9-90b0-6ecad794cfac.png)

**Comment by t-sommer** [comment] 2019-09-11 15:01
Please open a service request for Dymola for this issue. Closing this in favor of #68.

**Closed by t-sommer** 2019-09-11 15:01 UTC

**Comment by PhilippZofer** [comment] 2019-09-11 15:39
Because the offical website (https://www.3ds.com/products-services/catia/products/dymola/fmi/ ) states: 

> "Support and maintenance is offered to Dymola customers through the regular support channel at www.3ds.com/support."

the original service request was opened within the DSx-client a week ago. This service request was closed because FMI Kit is now provided freely on GitHub and is not part of the Dymola distribution. Therefore the support should be handled at GitHub as well. 
I will reopen the service request with DS again.

Thank you for keeping on with issue #68, which is also more important right now than this one.

**Comment by hv3ds** [comment] 2019-11-12 15:39
The problem is in "sources/fmiwrapper.inc": the FMU exports a set of arrays but getScalarVariable always return a pointer to the first element. This has the effect of rewriting every value to the first entry and as could be expected, Out1[1] takes the shape of Out1[5].

void *getScalarVariable(RT_MDL_TYPE *S, int vr, BuiltInDTypeId *dtypeID) {
  switch(vr) {
    case 1:
      *dtypeID = 0;
      return &(rtmGetDefaultParam(S)->SineWave_Amp);
    case 2:
      *dtypeID = 0;
      return &(rtmGetDefaultParam(S)->SineWave_Amp);

// … and so on ...
