### ISSUE TITLE
Export linux64 FMU in Windows systems

### ISSUE THREAD

**Issue by SallyTYT** [CATIA-Systems/FMIKit-Simulink#235] opened 2020-11-05 01:38 UTC
I'm working with MATLAB R2020a and FMIKit-2.8 in a Windows system. Is it possible to Export linux64 FMU in Windows systems? Thanks!

**Comment by t-sommer** [comment] 2020-11-25 09:08
Duplicate of #79

**Closed by t-sommer** 2020-11-25 09:08 UTC
Labels: question
